SocialNetwork.Web/SocialNetwork.Web/Models/MessageViewModel.cs
using SocialNetwork.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SocialNetwork.Web.Models
{
    public class MessageViewModel
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public string Text { get; set; }
        public DateTime SendOn { get; set; } = DateTime.Now;
        public int UserId { get; set; }
        public virtual User User { get; set; }
        public bool IsDeleted { get; set; }
    }
}

SocialNetwork.Web/SocialNetwork.Web/Controllers/AlbumController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SocialNetwork.Models;
using SocialNetwork.Services.Contracts;

namespace SocialNetwork.Web.Controllers
{
    public class AlbumController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IMapper _mapper;
        private readonly IUserService _userService;
        private readonly ICommentService _commentService;
        private readonly IContactService _contactService;
        private readonly IPhotoService _photoService;
        private readonly IPostService _postService;
        private readonly UserManager<User> _userManager;
        private readonly SignInManager<User> _signInManager;


        public AlbumController(IPostService postService, ICommentService commentService, ILogger<HomeController> logger, IMapper mapper, IContactService contactService, IPhotoService photoService, IUserService userService, SignInManager<User> signInManager, UserManager<User> userManager)
        {
            this._logger = logger;
            this._mapper = mapper;
            this._contactService = contactService;
            this._photoService = photoService;
            this._userService = userService;
            this._signInManager = signInManager;
            this._userManager = userManager;
            this._postService = postService;
            this._commentService = commentService;
        }
        // GET: Album
        public async Task<IActionResult> Album(int id)
        {
            var user = await _userService.GetUserAsync(id);

            string curr = _userManager.GetUserId(User);

            user.CurrentLoggedUserId = int.Parse(curr);

            return View(user);
        }
    }
}

SocialNetwork.Web/SocialNetwork.Web/Controllers/MessagesController.cs
using AutoMapper;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using SocialNetwork.Models;
using SocialNetwork.Services.Contracts;
using SocialNetwork.Services.DTOs;
using System.Threading.Tasks;

namespace SocialNetwork.Web.Controllers
{
    public class MessagesController : Controller
    {
        private readonly IMessageService _messageService;
        private readonly IUserService _userService;
        private readonly IMapper _mapper;
        private readonly UserManager<User> _userManager;
        private readonly SignInManager<User> _signInManager;

        public MessagesController(IMapper mapper, IUserService userService, IMessageService messageService, UserManager<User> userManager, SignInManager<User> signInManager)
        {
            this._mapper = mapper;
            this._userService = userService;
            this._messageService = messageService;
            this._userManager = userManager;
            this._signInManager = signInManager;
        }

        // GET: Messages
        public async Task<IActionResult> Index(int receiverId)
        {
            var user = _userManager.GetUserId(User);

            if (receiverId == 0)
            {
                var currentUser = await _userService.GetUserAsync(int.Parse(user));
                return View(currentUser);

            }
            else
            {
                var currentUser = await _userService.GetUserAsync(int.Parse(user));
                currentUser.CurrentLoggedUserId = receiverId;
                return View(currentUser);
            }




        }

        // GET: Messages/Details/5
        public async Task<IActionResult> Details(int id)
        {
            var message = await _messageService.GetMessageAsync(id);

            if (message == null)
            {
                return NotFound();
            }

            return View(message);
        }


        // POST: Messages/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(int userId, int receiverId, UserDTO userDTO)
        {
            if (ModelState.IsValid)
            {
                var messageDTO = _mapper.Map<MessageDTO>(userDTO);

                messageDTO.SenderId = userId;
                messageDTO.ReceiverId = receiverId;
                messageDTO.Text = userDTO.NewCommentContent;

                await _messageService.CreateMessageAsync(messageDTO);

                return RedirectToAction("Index", new { receiverId = receiverId });

            }
            //TODO
            return NotFound();
        }
    }
}

SocialNetwork.Web/SocialNetwork.Web/Views/Messages/Index.cshtml
@model SocialNetwork.Services.DTOs.UserDTO

@inject IUserService UserService
@inject UserManager<User> UserManager
@inject SignInManager<User> SignInManager



<div id="page-contents">
    <div class="container">
        <div class="row">

            <!-- Newsfeed Common Side Bar Left
            ================================================= -->
            <div class="col-md-3 static">
                <div class="profile-card">
                    <img src="~/images/@Model.ProfilePhoto" alt="user" class="profile-photo" />
                    <h5><a asp-controller="Home" asp-action="Index" class="text-white">@Model.FirstName @Model.LastName</a></h5>
                </div><!--profile card ends-->
                <ul class="nav-news-feed">
                    <li><i class="icon ion-ios-paper"></i><div><a asp-controller="Newsfeed" asp-action="Index">My Newsfeed</a></div></li>
                    <li><i class="icon ion-ios-people-outline"></i><div><a asp-controller="Home" asp-action="Friends">Friends</a></div></li>
                    <li><i class="icon ion-chatboxes"></i><div><a asp-controller="Messages" asp-action="Index">Messages</a></div></li>
                    <li><i class="icon ion-images"></i><div><a asp-controller="Album" asp-action="Album" asp-route-id="@Model.Id">Images</a></div></li>
                </ul><!--news-feed links ends-->
                <div id="chat-block">
                    <div class="title">Chat online</div>
                    <ul class="online-users list-inline">
                        @foreach (var friends in Model.Friends)
                        {
                            <li><a title="@friends.FirstName @friends.LastName"><img src="~/images/@friends.ProfilePhoto" alt="user" class="img-responsive profile-photo" /><span class="online-dot"></span></a></li>
                        }
                    </ul>
                </div>
                <!--chat block ends-->
            </div>

            <div class="col-md-7">
                <!-- Chat Room
                ================================================= -->
                @if (Model.Friends.Count != 0)
                {
                    UserDTO currentUser = new UserDTO();
                    UserDTO friend = new UserDTO();
                    <div class="chat-room">
                        <div class="row">
                            <div class="col-md-5">
                                <ul class="nav nav-tabs contact-list scrollbar-wrapper scrollbar-outer">
                                    @foreach (var user in Model.Friends)
                                    {
                                        if (Model.CurrentLoggedUserId == 0)
                                        {
                                            friend = await UserService.GetUserAsync(user.Id);
                                            currentUser = await UserService.GetUserAsync(user.Id);

                                        }
                                        else
                                        {
                                            friend = await UserService.GetUserAsync(user.Id);
                                            currentUser = await UserService.GetUserAsync(Model.CurrentLoggedUserId);
                                        }

                                        var sentMessages = Model.Messages.Where(x => x.SenderId == friend.Id || x.ReceiverId == friend.Id).ToList();
                                        var receivedMessages = friend.Messages.Where(x => x.SenderId == Model.Id || x.ReceiverId == Model.Id).ToList();

                                        var allMessages = sentMessages.Concat(receivedMessages).OrderBy(x => x.SendOn).ToList();
                                        <li class="active">
                                            @if (allMessages.Count == 0)
                                            {
                                                <a asp-controller="Messages" asp-action="Index" asp-route-userId="@Model.Id" asp-route-receiverId="@friend.Id">
                                                    <div class="contact">
                                                        <img src="~/images/@friend.ProfilePhoto" alt="" class="profile-photo-sm pull-left" />
                                                        <div class="msg-preview">
                                                            <h6>@friend.FirstName @friend.LastName</h6>
                                                            <p class="text-muted">No messages yet...</p>
                                                        </div>
                                                    </div>
                                                </a>

                                            }
                                            else
                                            {
                                                <!-- Contact List in Left-->
                                                <a asp-controller="Messages" asp-action="Index" asp-route-userId="@Model.Id" asp-route-receiverId="@friend.Id">
                                                    <div class="contact">
                                                        <img src="~/images/@friend.ProfilePhoto" alt="" class="profile-photo-sm pull-left" />
                                                        <div class="msg-preview">
                                                            <h6>@friend.FirstName</h6>
                                                            <p class="text-muted">@allMessages.Last().Text</p>
                                                            <small class="text-muted">@allMessages.Last().SendOn</small>
                                                        </div>
                                                    </div>
                                                </a>

                                                <!--Contact List in Left End-->
                                            }
                                        </li>
                                    }
                                </ul>
                            </div>
                            <div class="col-md-7">

                                <!--Chat Messages in Right-->

                                <div class="tab-content scrollbar-wrapper wrapper scrollbar-outer">
                                    <div class="tab-pane active" id="@friend.Id">
                                        <div class="chat-body">
                                            @foreach (var messages in currentUser.Messages.Where(x => x.ReceiverId == Model.Id || x.SenderId == Model.Id).Concat(Model.Messages.Where(x => x.ReceiverId == currentUser.Id || x.SenderId == currentUser.Id)).OrderByDescending(x => x.SendOn))
                                            {
                                                <ul class="chat-message">
                                                    @if (messages.SenderId == Model.Id)
                                                    {
                                                        <li class="right">
                                                            <img src="~/images/@Model.ProfilePhoto" alt="" class="profile-photo-sm pull-right" />
                                                            <div class="chat-item">
                                                                <div class="chat-item-header">
                                                                    <h5>@Model.FirstName @Model.LastName</h5>
                                                                    <small class="text-muted">@messages.SendOn</small>
                                                                </div>
                                                                <p>@messages.Text</p>
                                                            </div>
                                                        </li>
                                                    }
                                                    else
                                                    {
                                                        <li class="left">
                                                            <img src="~/images/@messages.Sender.ProfilePhoto" alt="" class="profile-photo-sm pull-left" />
                                                            <div class="chat-item">
                                                                <div class="chat-item-header">
                                                                    <h5>@messages.Sender.FirstName @messages.Sender.LastName</h5>
                                                                    <small class="text-muted">@messages.SendOn</small>
                                                                </div>
                                                                <p>@messages.Text</p>
                                                            </div>
                                                        </li>
                                                    }
                                                </ul>
                                            }
                                        </div>
                                    </div>
                                </div><!--Chat Messages in Right End-->

                                <div class="send-message">
                                    <div class="input-group">
                                        <form asp-controller="Messages" asp-action="Create" asp-route-userId="@Model.Id" asp-route-receiverId="@currentUser.Id">
                                            <input asp-for="NewCommentContent" name="NewCommentContent" type="text" class="form-control" placeholder="Type your message">
                                            <button class="btn btn-success pull-right">Send</button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                            <div class="clearfix"></div>
                        </div>
                    </div>
                }
            </div>


            <!-- Newsfeed Common Side Bar Right
            ================================================= -->
            <div class="col-md-2 static pull-right">
                <div class="suggestions" id="sticky-sidebar">
                    <h4 class="grey">Add More Friends</h4>
                    @if (Model.Friends.Count == 0)
                    {
                        var users = await UserService.GetAllUsersAsync();
                        var userMe = users.Where(x => x.Id == int.Parse(UserManager.GetUserId(User))).FirstOrDefault();
                        var admin = users.Where(x => x.Id == 1).FirstOrDefault();
                        users.Remove(admin);
                        users.Remove(userMe);

                        foreach (var user in users.Take(5))
                        {
                            <img src="~/images/@user.ProfilePhoto" alt="" class="profile-photo-sm pull-left" />
                            <div>
                                <h5><a asp-controller="Home" asp-action="TimelineOfFriend" asp-route-id="@user.Id">@user.FirstName @user.LastName</a></h5>
                                <form asp-controller="Home" asp-action="SendFriendRequest" asp-route-messagesId="1" asp-route-newsfeed="0" asp-route-adresseeId="@user.Id">
                                    <button class="btn btn-primary pull-right">Send Request</button>
                                </form>
                            </div>
                        }
                    }
                    else
                    {
                        var users = await UserService.GetAllUsersAsync();
                        var admin = users.Where(x => x.Id == 1).FirstOrDefault();
                        users.Remove(admin);

                        var userMe = users.Where(x => x.Id == int.Parse(UserManager.GetUserId(User))).FirstOrDefault();
                        users.Remove(userMe);
                        @foreach (var friend in Model.Friends)
                        {
                            if (users.Any(x => x.Id == friend.Id))
                            {
                                var user = users.Where(x => x.Id == friend.Id).FirstOrDefault();
                                users.Remove(user);
                            }
                        }

                        foreach (var user in users.Take(5))
                        {
                            <img src="~/images/@user.ProfilePhoto" alt="" class="profile-photo-sm pull-left" />
                            <div>
                                <h5><a asp-controller="Home" asp-action="TimelineOfFriend" asp-route-id="@user.Id">@user.FirstName @user.LastName</a></h5>
                                <form asp-controller="Home" asp-action="SendFriendRequest" asp-route-messagesId="1" asp-route-newsfeed="0" asp-route-adresseeId="@user.Id">
                                    <button class="btn btn-primary pull-right">Send Request</button>
                                </form>
                            </div>
                        }
                    }

                </div>
            </div>
        </div>
    </div>
</div>