SocialNetwork.Web/SocialNetwork.Web/Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using SocialNetwork.Models;
using SocialNetwork.Services.Contracts;
using SocialNetwork.Services.DTOs;
using SocialNetwork.Web.Models;

namespace SocialNetwork.Web.Controllers
{
    public class AboutController : Controller
    {
        private readonly IMapper _mapper;
        private readonly IUserService _userService;
        private readonly UserManager<User> _userManager;
        public AboutController(IMapper mapper, UserManager<User> userManager, IUserService userService)
        {
            this._mapper = mapper;
            this._userManager = userManager;
            this._userService = userService;
        }
        // GET: AboutController
        public async Task<IActionResult> About(int id)
        {
            var user = await _userService.GetUserAsync(id);
            string curr = _userManager.GetUserId(User);

            user.CurrentLoggedUserId = int.Parse(curr);
            return View(user);
        }
    }
}

SocialNetwork.Web/SocialNetwork.Web/Controllers/AlbumController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SocialNetwork.Models;
using SocialNetwork.Services.Contracts;

namespace SocialNetwork.Web.Controllers
{
    public class AlbumController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IMapper _mapper;
        private readonly IUserService _userService;
        private readonly ICommentService _commentService;
        private readonly IContactService _contactService;
        private readonly IPhotoService _photoService;
        private readonly IPostService _postService;
        private readonly UserManager<User> _userManager;
        private readonly SignInManager<User> _signInManager;


        public AlbumController(IPostService postService, ICommentService commentService, ILogger<HomeController> logger, IMapper mapper, IContactService contactService, IPhotoService photoService, IUserService userService, SignInManager<User> signInManager, UserManager<User> userManager)
        {
            this._logger = logger;
            this._mapper = mapper;
            this._contactService = contactService;
            this._photoService = photoService;
            this._userService = userService;
            this._signInManager = signInManager;
            this._userManager = userManager;
            this._postService = postService;
            this._commentService = commentService;
        }
        // GET: Album
        public async Task<IActionResult> Album(int id)
        {
            var user = await _userService.GetUserAsync(id);

            string curr = _userManager.GetUserId(User);

            user.CurrentLoggedUserId = int.Parse(curr);

            return View(user);
        }
    }
}

SocialNetwork.Web/SocialNetwork.Web/Controllers/UserFriendsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using SocialNetwork.Database;
using SocialNetwork.Models;
using SocialNetwork.Services.Contracts;

namespace SocialNetwork.Web.Controllers
{
    public class UserFriendsController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IMapper _mapper;
        private readonly IUserService _userService;
        private readonly IUserFriendService _userFriendService;
        private readonly ICommentService _commentService;
        private readonly IContactService _contactService;
        private readonly IPhotoService _photoService;
        private readonly IPostService _postService;
        private readonly IWebHostEnvironment _environment;
        private readonly UserManager<User> _userManager;
        private readonly SignInManager<User> _signInManager;


        public UserFriendsController(IUserFriendService userFriendService, IPostService postService, ICommentService commentService, ILogger<HomeController> logger, IWebHostEnvironment environment, IMapper mapper, IContactService contactService, IPhotoService photoService, IUserService userService, SignInManager<User> signInManager, UserManager<User> userManager)
        {
            this._logger = logger;
            this._environment = environment;
            this._mapper = mapper;
            this._contactService = contactService;
            this._photoService = photoService;
            this._userService = userService;
            this._signInManager = signInManager;
            this._userManager = userManager;
            this._postService = postService;
            this._commentService = commentService;
            this._userFriendService = userFriendService;
        }

        public async Task<IActionResult> FriendRequests()
        {
            string curentUser = _userManager.GetUserId(User);

            var user = await _userService.GetUserAsync(int.Parse(curentUser));

            return View(user);
        }

        public async Task<IActionResult> Accept(int newsfeed, int timelineOfFriendId, int toAddId)
        {
            if (timelineOfFriendId == 0)
            {
                await _userFriendService.AcceptFriendRequest(toAddId);
                return RedirectToAction("FriendRequests", "UserFriends");
            }
            if (newsfeed != 0)
            {
                await _userFriendService.AcceptFriendRequest(toAddId);
                return RedirectToAction("Newsfeed", "Index");
            }
            else
            {
                await _userFriendService.AcceptFriendRequest(toAddId);
                return RedirectToAction("TimelineOfFriend", "Home", new { id = timelineOfFriendId});
            }

        }

        public async Task<IActionResult> Decline(int newsfeed, int timelineOfFriendId, int toAddId)
        {
            if (timelineOfFriendId == 0)
            {
                await _userFriendService.DeclineFriendRequest(toAddId);
                return RedirectToAction("FriendRequests", "UserFriends");
            }
            if (newsfeed != 0)
            {
                await _userFriendService.DeclineFriendRequest(toAddId);
                return RedirectToAction("Newsfeed", "Index");
            }
            else
            {
                await _userFriendService.DeclineFriendRequest(toAddId);
                return RedirectToAction("TimelineOfFriend", "Home", new { id = timelineOfFriendId });
            }
        }

        //TODO make all the actions return the needed view. Make new return options if you call the unfriend of the timeline of friend or friends view.
        public async Task<IActionResult> Unfriend(int newsfeed, int timelineOfFriendId, int Id)
        {
            if (timelineOfFriendId == 0)
            {
                await _userFriendService.RemoveFriend(Id);
                return RedirectToAction("FriendRequests", "UserFriends");
            }
            if (newsfeed != 0)
            {
                await _userFriendService.RemoveFriend(Id);
                return RedirectToAction("Newsfeed", "Index");
            }
            else
            {
                await _userFriendService.RemoveFriend(Id);
                return RedirectToAction("TimelineOfFriend", "Home", new { id = timelineOfFriendId });
            }
        }

    }
}

SocialNetwork.Web/SocialNetwork.Web/Views/UserFriends/FriendRequests.cshtml
@model SocialNetwork.Services.DTOs.UserDTO

@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager

<div class="container">
    <!-- Timeline
         ================================================= -->
    <div class="timeline-cover">
        <img src="~/images/@Model.CoverPhoto" class="img-responsive timeline-cover" />
        <!--Timeline Menu for Large Screens-->
        <div class="timeline-nav-bar hidden-sm hidden-xs">
            <div class="row">
                <div class="col-md-3">
                    <div class="profile-info">
                        <img src="~/images/@Model.ProfilePhoto" alt="" class="img-responsive profile-photo" />
                        <h3>@Model.FirstName @Model.LastName</h3>
                        <p class="text-info pull-left">
                            <div class="line-divider"></div>
                            @if (Model.JobTitle != null)
                            {
                                <div class="row pull-left">
                                    <a>
                                        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-briefcase-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                            <path fill-rule="evenodd" d="M0 12.5A1.5 1.5 0 0 0 1.5 14h13a1.5 1.5 0 0 0 1.5-1.5V6.85L8.129 8.947a.5.5 0 0 1-.258 0L0 6.85v5.65z" />
                                            <path fill-rule="evenodd" d="M0 4.5A1.5 1.5 0 0 1 1.5 3h13A1.5 1.5 0 0 1 16 4.5v1.384l-7.614 2.03a1.5 1.5 0 0 1-.772 0L0 5.884V4.5zm5-2A1.5 1.5 0 0 1 6.5 1h3A1.5 1.5 0 0 1 11 2.5V3h-1v-.5a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5V3H5v-.5z" />
                                        </svg> Works as @Model.JobTitle
                                    </a>
                                    <div class="line-divider"></div>
                                </div>
                            }
                            @if (Model.City != null)
                            {
                                <div class="row pull-left">
                                    <a>
                                        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-geo-alt-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                            <path fill-rule="evenodd" d="M8 16s6-5.686 6-10A6 6 0 0 0 2 6c0 4.314 6 10 6 10zm0-7a3 3 0 1 0 0-6 3 3 0 0 0 0 6z" />
                                        </svg> Lives in @Model.City, @Model.Country.Name
                                    </a>
                                    <div class="line-divider"></div>
                                </div>
                            }
                            @if (Model.Education != null)
                            {
                                <div class="row pull-left">
                                    <a>
                                        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-award-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                            <path d="M8 0l1.669.864 1.858.282.842 1.68 1.337 1.32L13.4 6l.306 1.854-1.337 1.32-.842 1.68-1.858.282L8 12l-1.669-.864-1.858-.282-.842-1.68-1.337-1.32L2.6 6l-.306-1.854 1.337-1.32.842-1.68L6.331.864 8 0z" />
                                            <path d="M4 11.794V16l4-1 4 1v-4.206l-2.018.306L8 13.126 6.018 12.1 4 11.794z" />
                                        </svg> Studied at @Model.Education
                                    </a>
                                    <div class="line-divider"></div>
                                </div>
                            }
                            @if (Model.DateOfBirth != null && Model.MonthOfBirth != null && Model.YearOfBirth != null)
                            {
                                <div class="row pull-left">
                                    <a>
                                        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-calendar-check-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                            <path fill-rule="evenodd" d="M4 .5a.5.5 0 0 0-1 0V1H2a2 2 0 0 0-2 2v1h16V3a2 2 0 0 0-2-2h-1V.5a.5.5 0 0 0-1 0V1H4V.5zM16 14V5H0v9a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2zm-5.146-5.146a.5.5 0 0 0-.708-.708L7.5 10.793 6.354 9.646a.5.5 0 1 0-.708.708l1.5 1.5a.5.5 0 0 0 .708 0l3-3z" />
                                        </svg> Born on @Model.DateOfBirth/@Model.MonthOfBirth/@Model.YearOfBirth
                                    </a>
                                    <div class="line-divider"></div>
                                </div>
                            }
                            @if (Model.Biography != null)
                            {
                                <div class="row pull-left">
                                    <a>
                                        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-layers-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                            <path fill-rule="evenodd" d="M7.765 1.559a.5.5 0 0 1 .47 0l7.5 4a.5.5 0 0 1 0 .882l-7.5 4a.5.5 0 0 1-.47 0l-7.5-4a.5.5 0 0 1 0-.882l7.5-4z" />
                                            <path fill-rule="evenodd" d="M2.125 8.567l-1.86.992a.5.5 0 0 0 0 .882l7.5 4a.5.5 0 0 0 .47 0l7.5-4a.5.5 0 0 0 0-.882l-1.86-.992-5.17 2.756a1.5 1.5 0 0 1-1.41 0l-5.17-2.756z" />
                                        </svg> Biography: @Model.Biography
                                    </a>
                                    <div class="line-divider"></div>
                                </div>
                            }
                        </p>
                    </div>
                </div>
                <div class="col-md-9">
                    <ul class="list-inline profile-menu">
                        <li><a asp-controller="Home" asp-action="Timeline">Timeline</a></li>
                        <li><a asp-controller="About" asp-action="About" asp-route-id="@Model.Id">About</a></li>
                        <li><a asp-controller="Album" asp-action="Album" asp-route-id="@Model.Id">Album</a></li>
                        <li><a asp-controller="Home" asp-action="Friends" asp-route-id="@Model.Id">Friends</a></li>
                        <li><a asp-controller="UserFriends" asp-action="FriendRequests" class="active">Friend Requests</a></li>
                        <li><a asp-controller="Friends" asp-action="Index" asp-route-id="@Model.Id">Add Friends</a></li>
                    </ul>
                </div>
            </div>
        </div><!--Timeline Menu for Large Screens End-->
        <!--Timeline Menu for Small Screens-->
        <div class="navbar-mobile hidden-lg hidden-md">
            <div class="profile-info">
                <img src="~/images/@Model.ProfilePhoto" alt="" class="img-responsive profile-photo" />
                <h4>@Model.FirstName @Model.LastName</h4>
                <p class="text-muted">@Model.JobTitle</p>
            </div>
            <div class="mobile-menu">
                <ul class="list-inline">
                    <li><a asp-controller="Home" asp-action="Timeline" class="active">Timeline</a></li>
                    <li><a asp-controller="About" asp-action="About">About</a></li>
                    <li><a asp-controller="Album" asp-action="Album" asp-route-id="@Model.Id" class="active">Album</a></li>
                    <li><a asp-controller="UserFriends" asp-action="FriendRequests" class="active">Friend Requests</a></li>
                    <li><a asp-controller="Friends" asp-action="Index" asp-route-id="@Model.Id">Add Friends</a></li>
                </ul>
            </div>
        </div><!--Timeline Menu for Small Screens End-->

    </div>
    <div id="page-contents">
        <div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-7">
                <!-- Post Content
                ================================================= -->
                @foreach (var requester in Model.RequestersUserFriends.Where(x => x.IsAccepted == false && x.IsRemoved == false))
                {
                    <div class="friend-list">
                        <div class="row">
                            <div class="col-md-6 col-sm-6">
                                <div class="friend-card">
                                    <img src="~/images/@requester.Requester.CoverPhoto" alt="profile-cover" class="img-responsive cover" />
                                    <div class="card-info">
                                        <img src="~/images/@requester.Requester.ProfilePhoto" alt="user" class="profile-photo-lg" />
                                        <div class="friend-info">
                                            <h5><a asp-controller="Home" asp-action="TimelineOfFriend" asp-route-id="@requester.RequesterId" class="profile-link">@requester.Requester.FirstName @requester.Requester.LastName</a></h5>
                                            <p>@requester.Requester.JobTitle</p>
                                            <div class="line-divider"></div>
                                            <form asp-controller="UserFriends" asp-action="Accept" asp-route-toAddId="@requester.Id">
                                                    <button class="ml-custom-2 btn btn-success pull-right">Accept</button>
                                            </form>
                                            <form asp-controller="UserFriends" asp-action="Decline" asp-route-toAddId="@requester.Id">
                                                <button class="ml-2 btn btn-danger pull-right">Decline</button>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                }

            </div>

            <div class="col-md-2 static">
                <div id="sticky-sidebar">
                    <h4 class="grey">@Model.FirstName's activity:</h4>
                    @foreach (var item in Model.HistoryLog.OrderByDescending(x => x.Id))
                    {
                        <div class="feed-item">
                            <div class="live-activity">
                                <p><a class="profile-link"></a>@item.Content</p>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>